[package]
name = "banquero"
version = "0.1.0"
authors = ["Jazmin Ferreiro <jazminsofiaf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rand = "0.7.3"
math = "0.0.2"
